name: Java Maven CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [11, 17, 21]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Verify Maven wrapper
        run: |
          if [ -f "mvnw" ]; then
            chmod +x mvnw
            echo "Using Maven wrapper"
            MVN_CMD="./mvnw"
          else
            echo "No Maven wrapper found, using system Maven"
            MVN_CMD="mvn"
          fi
          echo "MVN_CMD=$MVN_CMD" >> $GITHUB_ENV

      - name: Build with Maven
        run: ${{ env.MVN_CMD }} clean verify -B -V

      - name: Run tests
        run: ${{ env.MVN_CMD }} test -B

      - name: Generate JaCoCo coverage report
        if: matrix.java-version == 17
        run: ${{ env.MVN_CMD }} jacoco:report

      - name: Upload coverage to Codecov
        if: matrix.java-version == 17
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./target/site/jacoco/jacoco.xml
          flags: unittests
          name: java-maven-${{ matrix.java-version }}

      - name: Upload build artifacts
        if: matrix.java-version == 17
        uses: actions/upload-artifact@v4
        with:
          name: maven-artifacts
          path: target/*.jar
          retention-days: 7

  security-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Verify Maven wrapper
        run: |
          if [ -f "mvnw" ]; then
            chmod +x mvnw
            echo "MVN_CMD=./mvnw" >> $GITHUB_ENV
          else
            echo "MVN_CMD=mvn" >> $GITHUB_ENV
          fi

      - name: OWASP Dependency-Check
        run: |
          ${{ env.MVN_CMD }} org.owasp:dependency-check-maven:check
        continue-on-error: true

      - name: SpotBugs analysis
        run: |
          ${{ env.MVN_CMD }} compile spotbugs:check
        continue-on-error: true

      - name: Upload SpotBugs report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report
          path: target/spotbugsXml.xml
          retention-days: 7

      - name: GitLeaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: SonarCloud scan
        if: env.SONAR_TOKEN != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          if [ -f "mvnw" ]; then
            chmod +x mvnw
            ./mvnw verify sonar:sonar \
              -Dsonar.projectKey=${{ github.repository_owner }}_${{ github.event.repository.name }} \
              -Dsonar.organization=${{ github.repository_owner }} \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.token=${{ secrets.SONAR_TOKEN }}
          else
            mvn verify sonar:sonar \
              -Dsonar.projectKey=${{ github.repository_owner }}_${{ github.event.repository.name }} \
              -Dsonar.organization=${{ github.repository_owner }} \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.token=${{ secrets.SONAR_TOKEN }}
          fi
